apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.name }}-{{ .Values.pullRequest }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
  - port: 8080
    name: http-port
